<!DOCTYPE html><html>
        <head>
        <title>2019 Fall 電腦輔助設計實習課程網頁</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700,900" rel="stylesheet">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/fonts/icomoon/style.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/bootstrap.min.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/magnific-popup.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/jquery-ui.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/owl.carousel.min.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/owl.theme.default.min.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/bootstrap-datepicker.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/fonts/flaticon/font/flaticon.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/aos.css">
        <link rel="stylesheet" href="./../cmsimde/static/chimper/css/style.css">
        <link rel="shortcut icon" href="./../cmsimde/static/favicons.png">
        
        <style type='text/css'>
            .site-section {
            background-color: #FFFF;
            padding: 40px 40px;
            }
            body > div > div.dropdown.open {
                display: block;
            }
        </style>
    
        <!-- <script src="./../cmsimde/static/jquery.js"></script> -->
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
        <script src="../cmsimde/static/chimper/js/jquery-3.3.1.min.js"></script>
        <link rel="stylesheet" href="./../cmsimde/static/tipuesearch/css/normalize.min.css">
        <script src="./../cmsimde/static/tipuesearch/tipuesearch_set.js"></script>
        <script src="tipuesearch_content.js"></script>
        <link rel="stylesheet" href="./../cmsimde/static/tipuesearch/css/tipuesearch.css">
        <script src="./../cmsimde/static/tipuesearch/tipuesearch.js"></script>
        <script>
            /* original tipuesearch
            $(document).ready(function() {
                 $('#tipue_search_input').tipuesearch();
            });
            */
            // customed doSearch
            function doSearch() {
                $('#tipue_search_input').tipuesearch({
                    newWindow: true, 
                    minimumLength: 2,
                    wholeWords: false, // for search 中文
                });
            }
            $(document).ready(doSearch);
        </script>
        
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shCore.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushJScript.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushJava.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushPython.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushSql.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushHaxe.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushXml.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushPhp.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushLua.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushCpp.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushCss.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushCSharp.js"></script>
<script type="text/javascript" src="./../cmsimde/static/syntaxhighlighter/shBrushDart.js"></script>
<link type="text/css" rel="stylesheet" href="./../cmsimde/static/syntaxhighlighter/css/shCoreDefault.css"/>
<script type="text/javascript">SyntaxHighlighter.all();</script>

<!-- 啟用 LaTeX equations 編輯 -->
<script src="https://scrum-3.github.io/web/math/MathJax.js?config=TeX-MML-AM_CHTML" type="text/javascript"></script>
<script type="text/javascript">
init_mathjax = function() {
    if (window.MathJax) {
        // MathJax loaded
        MathJax.Hub.Config({
            tex2jax: {
                inlineMath: [ ['$','$'], ["\\(","\\)"] ],
                displayMath: [ ['$$','$$'], ["\\[","\\]"] ]
            },
            displayAlign: 'left', // Change this to 'center' to center equations.
            "HTML-CSS": {
                styles: {'.MathJax_Display': {"margin": 0}}
            }
        });
        MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
    }
}
init_mathjax();
</script>

<!-- 暫時不用
<script src="./../cmsimde/static/fengari-web.js"></script>
<script type="text/javascript" src="./../cmsimde/static/Cango-13v08-min.js"></script>
<script type="text/javascript" src="./../cmsimde/static/CangoAxes-4v01-min.js"></script>
<script type="text/javascript" src="./../cmsimde/static/gearUtils-05.js"></script>
-->
<!-- for Brython 暫時不用
<script src="https://scrum-3.github.io/web/brython/brython.js"></script>
<script src="https://scrum-3.github.io/web/brython/brython_stdlib.js"></script>
-->
<style>
img.add_border {
    border: 3px solid blue;
}
</style>

</head>
<body>
<div class='container'><nav>
        
    <div class="site-wrap">

    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
    
            <header class="site-navbar py-4 bg-white" role="banner">
              <div class="container-fluid">
                <div class="row align-items-center">
                <h1>2019 Fall 電腦輔助設計實習課程網頁</h1>
                <div class="pl-4">
                    <form>
                    <input type="text" placeholder="Search" name="q" id="tipue_search_input" pattern=".{2,}" title="At least 2 characters" required>
                    </form>
                </div>
                  <!-- <div class="col-11 col-xl-2">
                    <h1 class="mb-0 site-logo"><a href="index.html" class="text-black h2 mb-0">2019 Fall 電腦輔助設計實習課程網頁</a></h1> 
                  </div>
                  -->
                  <div class="col-12 col-md-10 d-none d-xl-block">
                    <nav class="site-navigation position-relative text-right" role="navigation">
    <ul class='site-menu js-clone-nav mr-auto d-none d-lg-block'>
                        <li class="active has-children"><a href="index.html">Home</a>
                        <ul class="dropdown">
                            <li><a href="sitemap.html">Site Map</a></li>
                            <li><a href="./../reveal/index.html">reveal</a></li>
                            <li><a href="./../blog/index.html">blog</a></li>
                        </ul>
                      </li>
                     <li class='has-children'><a href='About.html'>About</a><ul class='dropdown'><li><a href='CAD Process.html'>CAD Process</a><li><a href='Evaluation.html'>Evaluation</a><li><a href='課程表單.html'>課程表單</a><li class='has-children'><a href='Theories.html'>Theories</a><ul class='dropdown'><li><a href='Design Theory.html'>Design Theory</a><li><a href='Optimal Design.html'>Optimal Design</a><li><a href='Cloud MCAD.html'>Cloud MCAD</a><li><a href='Generative Design.html'>Generative Design</a></li></li></ul></ul><li class='has-children'><a href='CMS.html'>CMS</a><ul class='dropdown'><li class='has-children'><a href='CMSiMDE.html'>CMSiMDE</a><ul class='dropdown'><li><a href='CMSiMDE 已知錯誤.html'>CMSiMDE 已知錯誤</a></li></ul><li class='has-children'><a href='STL.html'>STL</a><ul class='dropdown'><li><a href='Trimesh.html'>Trimesh</a></li></li></ul></ul><li class='has-children'><a href='Tools.html'>Tools</a><ul class='dropdown'><li><a href='FFmpeg.html'>FFmpeg</a><li><a href='GUI.html'>GUI</a><li><a href='Solvespace.html'>Solvespace</a><li class='has-children'><a href='Pyslvs-UI.html'>Pyslvs-UI</a><ul class='dropdown'><li><a href='Pyside2.html'>Pyside2</a></li></ul><li><a href='Onshape.html'>Onshape</a><li class='has-children'><a href='V-rep.html'>V-rep</a><ul class='dropdown'><li><a href='V-rep Manual.html'>V-rep Manual</a><li><a href='3D Printer.html'>3D Printer</a><li><a href='Cyber-physical.html'>Cyber-physical</a></li></ul><li><a href='FreeCAD.html'>FreeCAD</a><li class='has-children'><a href='Webots.html'>Webots</a><ul class='dropdown'><li><a href='VRML.html'>VRML</a><li><a href='SciTE.html'>SciTE</a><li><a href='Webots Doc.html'>Webots Doc</a><li><a href='Robot Curriculum.html'>Robot Curriculum</a><li><a href='Three.js.html'>Three.js</a></li></ul><li class='has-children'><a href='Solidworks.html'>Solidworks</a><ul class='dropdown'><li><a href='SW API.html'>SW API</a></li></ul><li><a href='Libfivepy.html'>Libfivepy</a><li><a href='NX.html'>NX</a><li><a href='NX12 程式.html'>NX12 程式</a><li><a href='TeX.html'>TeX</a><li><a href='Open CAX.html'>Open CAX</a><li><a href='Bond Graphs.html'>Bond Graphs</a></li></ul><li class='has-children'><a href='Tasks.html'>Tasks</a><ul class='dropdown'><li><a href='分組名單.html'>分組名單</a><li class='has-children'><a href='Task1.html'>Task1</a><ul class='dropdown'><li><a href='Solvespace 編譯.html'>Solvespace 編譯</a><li><a href='Solvespace 操作.html'>Solvespace 操作</a><li><a href='機構設計與模擬.html'>機構設計與模擬</a><li><a href='GCS.html'>GCS</a></li></ul><li class='has-children'><a href='Task2.html'>Task2</a><ul class='dropdown'><li><a href='導入 GitExtensions.html'>導入 GitExtensions</a><li><a href='Batch Command.html'>Batch Command</a></li></ul><li class='has-children'><a href='Task3.html'>Task3</a><ul class='dropdown'><li><a href='WB Tutorial1.html'>WB Tutorial1</a><li><a href='W16 Exam.html'>W16 Exam</a><li><a href='W17 Exan.html'>W17 Exan</a></li></ul><li><a href='Project.html'>Project</a></li></ul><li class='has-children'><a href='Reference.html'>Reference</a><ul class='dropdown'><li><a href='Documentary.html'>Documentary</a><li><a href='Ebooks.html'>Ebooks</a><li class='has-children'><a href='Planar Linkage.html'>Planar Linkage</a><ul class='dropdown'><li><a href='Design of Machinary.html'>Design of Machinary</a><li><a href='Graph Grammar.html'>Graph Grammar</a><li><a href='PMKS.html'>PMKS</a></li></ul><li><a href='Robotics Lib.html'>Robotics Lib</a><li><a href='CAD2CAE.html'>CAD2CAE</a></li>
                      </ul>
                </nav>
              </div>
              <div class="d-inline-block d-xl-none ml-md-0 mr-auto py-3" style="position: relative; top: 3px;"><a href="#" class="site-menu-toggle js-menu-toggle text-black"><span class="icon-menu h3"></span></a></div>
              </div>

            </div>
          </div>
          
        </header>
    <div id="tipue_search_content">NX << <a href='NX.html'>Previous</a> <a href='TeX.html'>Next</a> >> TeX<br /><h1>NX12 程式</h1>
<p><a href="./../downloads/NX-12-for-Engineering-Design.pdf">NX12 for Engineering Design.pdf</a> -&gt; 分組任務: 根據 <a href="https://link.springer.com/book/10.1007/978-3-319-03862-9">2015- Space Modeling with SolidWorks and NX</a><span> 中的 NX 資料與本電子書內容, 完成中英文並列的 <span style="background-color: #ffff00;">NX12 教學導引分組報告.</span></span></p>
<h4>NXOpen</h4>
<p style="padding-left: 30px;"><a href="https://docs.plm.automation.siemens.com/tdoc/nx/12/release_notes/#uid:index_xid850184:xid862140:xid385122">NX12 NXOpen 支援程式版本</a></p>
<p style="padding-left: 30px;"><a href="./../downloads/nxopen_getting_started_v12.pdf">nxopen_getting_started_v12.pdf</a> - 分組任務: 將本電子書中的 .NET 範例改寫為 <span style="background-color: #ffff00;">NXOpen Python 版本範例</span>, 並提供每一個程式範例的執行教學影片.</p>
<p style="padding-left: 30px;"><a href="./../downloads/Setup_Eclipse_for_NXOpenPythonScripting.pdf">Setup_Eclipse_for_NXOpenPythonScripting.pdf</a></p>
<p style="padding-left: 30px;"><a href="https://docs.plm.automation.siemens.com/data_services/resources/nx/12/nx_api/custom/en_US/nxopen_python_ref/index.html">https://docs.plm.automation.siemens.com/data_services/resources/nx/12/nx_api/custom/en_US/nxopen_python_ref/index.html</a></p>
<p style="padding-left: 30px;"><a href="http://nxjournaling.com/">http://nxjournaling.com/</a></p>
<p style="padding-left: 30px;"><a href="https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fwww.eng-tips.com%2F+nxopen+python">eng-tips.com about NXOpen and Python</a></p>
<p style="padding-left: 30px;"><a href="https://docs.plm.automation.siemens.com/tdoc/nx/12/nx_api/#uid:xid862706">run_journal 指令</a>可以直接執行外部的 NXOpen Python Journal 程式</p>
<p><iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/UCf8RG-st34" width="560"></iframe></p>
<p><iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/-5c1hRNXSco" width="560"></iframe></p>
<p><iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/ZMR8yDGrx_4" width="560"></iframe></p>
<p><iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/C1jQc4Pjb4c" width="560"></iframe></p>
<p><iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/jgewt4VixvA" width="560"></iframe></p>
<h4>環境變數</h4>
<pre class="brush:js;auto-links:false;toolbar:false" contenteditable="false">REM nx use python 3.6.1
REM Python 位於 Y:\NX12\NXBIN\python
set PYTHONPATH=y:\py373;Y:\NX12\NXBIN\python
set UGII_PYTHON_HOME=y:\py373;Y:\NX12\NXBIN\python
set UGII_PYTHON_LIBRARY_DIR=y:\py373
set UGII_PYTHONPATH=y:\py373;y:\py373\dlls;y:\py373\libs;y:\py373\lib;y:\py373\lib\site-packages
set UGII_PYTHON_DLL=python37.dll
set TCL_LIBRARY=y:\py373\tcl\tcl8.6</pre>
<h4>NXOpen Python Remote</h4>
<p style="padding-left: 30px;"><a href="https://docs.plm.automation.siemens.com/data_services/resources/nx/12/nx_api/custom/en_US/nxopen_python_ref/NXOpen.RemoteUtilities.html">https://docs.plm.automation.siemens.com/data_services/resources/nx/12/nx_api/custom/en_US/nxopen_python_ref/NXOpen.RemoteUtilities.html</a></p>
<p style="padding-left: 30px;">.Net 相關範例: Y:\NX12\UGOPEN\SampleNXOpenApplications\.NET\RemotingExample</p>
<p>File -&gt; Preferences -&gt; User Interface -&gt; Tools - &gt; Journal 可以將 Journal Language 設為 Python.</p>
<p>Menu -&gt; Tools -&gt; Journal 可以選擇錄製 Journal File.</p>
<p>利用 Menu -&gt; Tools -&gt; Journal 可以選擇 play 所錄製的 .py Journal File, 點選 Play 後, 選擇所要執行的 .py Journal 檔案後, 按下 Run 執行.</p>
<p>利用  NXOpen API Python 程式建立 Cube:</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false"># NX 12.0.2.9

#
import math
import NXOpen
import NXOpen.Annotations
import NXOpen.Features
import NXOpen.GeometricUtilities
import NXOpen.Preferences

def main() : 

    theUI = NXOpen.UI.GetUI()
    theMsgBox = theUI.NXMessageBox
    theMsgBox.Show("簡要說明", NXOpen.NXMessageBox.DialogType.Information,"以下流程將建立一個簡單的長方體")

    theSession  = NXOpen.Session.GetSession()

    # 以下利用 ListingWindow 列出相關資訊, 可用於程式除錯
    theLw = theSession.ListingWindow
    # 開啟 console 將資料印出
    theLw.Open()
    theLw.WriteLine("theSession 變數目前為: "+str(theSession))

    workPart = theSession.Parts.Work
    # ----------------------------------------------
    #   Menu: Insert-&gt;Sketch...
    # ----------------------------------------------
    markId1 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Start")
    
    sketchInPlaceBuilder1 = workPart.Sketches.CreateSketchInPlaceBuilder2(NXOpen.Sketch.Null)
    
    origin1 = NXOpen.Point3d(0.0, 0.0, 0.0)
    normal1 = NXOpen.Vector3d(0.0, 0.0, 1.0)
    plane1 = workPart.Planes.CreatePlane(origin1, normal1, NXOpen.SmartObject.UpdateOption.WithinModeling)
    
    sketchInPlaceBuilder1.PlaneReference = plane1
    
    unit1 = workPart.UnitCollection.FindObject("MilliMeter")
    
    sketchAlongPathBuilder1 = workPart.Sketches.CreateSketchAlongPathBuilder(NXOpen.Sketch.Null)

    datumAxis1 = workPart.Datums.FindObject("DATUM_CSYS(0) X axis")
    direction1 = workPart.Directions.CreateDirection(datumAxis1, NXOpen.Sense.Forward, NXOpen.SmartObject.UpdateOption.WithinModeling)
    
    datumPlane1 = workPart.Datums.FindObject("DATUM_CSYS(0) XY plane")
    datumCsys1 = workPart.Features.FindObject("DATUM_CSYS(0)")
    point1 = datumCsys1.FindObject("POINT 1")
    xform1 = workPart.Xforms.CreateXformByPlaneXDirPoint(datumPlane1, direction1, point1, NXOpen.SmartObject.UpdateOption.WithinModeling, 0.625, False, False)
    
    cartesianCoordinateSystem1 = workPart.CoordinateSystems.CreateCoordinateSystem(xform1, NXOpen.SmartObject.UpdateOption.WithinModeling)
    
    sketchInPlaceBuilder1.Csystem = cartesianCoordinateSystem1

    origin3 = NXOpen.Point3d(0.0, 0.0, 0.0)
    normal3 = NXOpen.Vector3d(0.0, 0.0, 1.0)
    plane3 = workPart.Planes.CreatePlane(origin3, normal3, NXOpen.SmartObject.UpdateOption.WithinModeling)
    
    plane3.SetMethod(NXOpen.PlaneTypes.MethodType.Coincident)
    
    geom2 = [NXOpen.NXObject.Null] * 1 
    geom2[0] = datumPlane1
    plane3.SetGeometry(geom2)
    
    plane3.SetAlternate(NXOpen.PlaneTypes.AlternateType.One)
    
    plane3.Evaluate()

    # ----------------------------------------------
    #   Menu: Insert-&gt;Sketch Curve-&gt;Rectangle...
    # ----------------------------------------------

    markId3 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Create Sketch")

    nXObject1 = sketchInPlaceBuilder1.Commit()
    
    sketch1 = nXObject1
    feature1 = sketch1.Feature
    
    sketch1.Activate(NXOpen.Sketch.ViewReorient.TrueValue)
    
    theSession.DeleteUndoMark(markId3, None)
    
    theSession.SetUndoMarkName(markId1, "Create Sketch")
    
    sketchInPlaceBuilder1.Destroy()
    
    sketchAlongPathBuilder1.Destroy()
        
    plane3.DestroyPlane()
    
    markId5 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Profile short list")
    
    markId6 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Create Rectangle")
    
    theSession.SetUndoMarkVisibility(markId6, "Create Rectangle", NXOpen.Session.MarkVisibility.Visible)
    
    # ----------------------------------------------
    # Creating rectangle using By 2 Points method 
    # ----------------------------------------------
    startPoint1 = NXOpen.Point3d(-52.0, 42.0, 0.0)
    endPoint1 = NXOpen.Point3d(44.0, 42.0, 0.0)
    line1 = workPart.Curves.CreateLine(startPoint1, endPoint1)
    
    startPoint2 = NXOpen.Point3d(44.0, 42.0, 0.0)
    endPoint2 = NXOpen.Point3d(44.0, -42.0, 0.0)
    line2 = workPart.Curves.CreateLine(startPoint2, endPoint2)
    
    startPoint3 = NXOpen.Point3d(44.0, -42.0, 0.0)
    endPoint3 = NXOpen.Point3d(-52.0, -42.0, 0.0)
    line3 = workPart.Curves.CreateLine(startPoint3, endPoint3)
    
    startPoint4 = NXOpen.Point3d(-52.0, -42.0, 0.0)
    endPoint4 = NXOpen.Point3d(-52.0, 42.0, 0.0)
    line4 = workPart.Curves.CreateLine(startPoint4, endPoint4)
    
    theSession.ActiveSketch.AddGeometry(line1, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
    
    theSession.ActiveSketch.AddGeometry(line2, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
    
    theSession.ActiveSketch.AddGeometry(line3, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
    
    theSession.ActiveSketch.AddGeometry(line4, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)

    theSession.ActiveSketch.Update()
    
    theSession.Preferences.Sketch.AutoDimensionsToArcCenter = True
    
    geoms1 = [NXOpen.SmartObject.Null] * 4 
    geoms1[0] = line1
    geoms1[1] = line2
    geoms1[2] = line3
    geoms1[3] = line4
    theSession.ActiveSketch.UpdateConstraintDisplay(geoms1)
    # ----------------------------------------------
    #   Menu: File-&gt;Finish Sketch
    # ----------------------------------------------
    sketch2 = theSession.ActiveSketch
    # ----------------------------------------------
    #   Menu: Insert-&gt;Design Feature-&gt;Extrude...
    # ----------------------------------------------
    markId8 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Start")
    
    extrudeBuilder1 = workPart.Features.CreateExtrudeBuilder(NXOpen.Features.Feature.Null)
    
    section1 = workPart.Sections.CreateSection(0.0094999999999999998, 0.01, 0.5)
    
    extrudeBuilder1.Section = section1
    
    extrudeBuilder1.AllowSelfIntersectingSection(True)
    
    unit2 = extrudeBuilder1.Draft.FrontDraftAngle.Units
  
    features1 = [NXOpen.Features.Feature.Null] * 1 
    sketchFeature1 = feature1
    features1[0] = sketchFeature1
    curveFeatureRule1 = workPart.ScRuleFactory.CreateRuleCurveFeature(features1)
    
    section1.AllowSelfIntersection(True)
    
    rules1 = [None] * 1 
    rules1[0] = curveFeatureRule1
    helpPoint1 = NXOpen.Point3d(-52.0, 18.603986789941445, 3.5527136788005009e-15)
    section1.AddToSection(rules1, line4, NXOpen.NXObject.Null, NXOpen.NXObject.Null, helpPoint1, NXOpen.Section.Mode.Create, False)

    direction2 = workPart.Directions.CreateDirection(sketch2, NXOpen.Sense.Forward, NXOpen.SmartObject.UpdateOption.WithinModeling)
    
    extrudeBuilder1.Direction = direction2
    
    extrudeBuilder1.Limits.EndExtend.Value.RightHandSide = "50"

    extrudeBuilder1.ParentFeatureInternal = False
    
    feature2 = extrudeBuilder1.CommitFeature()

    # ----------------------------------------------
    #   Menu: Tools-&gt;Journal-&gt;Stop Recording
    # ----------------------------------------------
    
if __name__ == '__main__':
    main()</pre>
<h4>bounding_box.py</h4>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">import NXOpen
import NXOpen.UF

theSession = NXOpen.Session.GetSession()
theLw = theSession.ListingWindow
theUI = NXOpen.UI.GetUI()
theUfSession = NXOpen.UF.UFSession.GetUFSession()

def main(*args): 

    workPart = theSession.Parts.BaseWork

    bodies = workPart.Bodies

    for body in bodies:

        (min_corner, directions, distances) = theUfSession.ModlGeneral.AskBoundingBoxExact(body.Tag, 0)

        theLw.Open()
        theLw.WriteLine("Bounding box for " + body.JournalIdentifier)

        theLw.WriteLine("  Min Corner: ")
        theLw.WriteLine("    X: " + str(min_corner[0]))
        theLw.WriteLine("    Y: " + str(min_corner[1]))
        theLw.WriteLine("    Z: " + str(min_corner[2]))

        theLw.WriteLine("  Direction Vectors: ")
        theLw.WriteLine("    X: (" + str(directions[0][0]) + ", " + str(directions[0][1]) + ", " + str(directions[0][2]) + ")")
        theLw.WriteLine("    Y: (" + str(directions[1][0]) + ", " + str(directions[1][1]) + ", " + str(directions[1][2]) + ")")
        theLw.WriteLine("    Z: (" + str(directions[2][0]) + ", " + str(directions[2][1]) + ", " + str(directions[2][2]) + ")")

        theLw.WriteLine("  Distances: ")
        theLw.WriteLine("    X: " + str(distances[0]))
        theLw.WriteLine("    Y: " + str(distances[1]))
        theLw.WriteLine("    Z: " + str(distances[2]))

        theLw.WriteLine("")

# Main program.

if __name__ == "__main__":
    main()
</pre>
<p>上述 NXOpen Python Journal 程式必須在 NX12 GUI 模式下執行, 若需要直接透過 Non-GUI 的模式執行 NXOpen Python Journal 程式, 則必須提供程式執行對應檔案, 並在執行完成後將結果存檔.</p>
<p>下列程式, 可以在隨身 NX12 程式可執行的環境中, 提供空白的 newPart.prt 檔案, 然後在命令列透過 run_journal create_cube.py, 建立所需的 cube.prt 立方體檔案.</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false"># NX 12.0.2.9
# 提供空檔案 newPart.prt
# 利用 run_journal journal_newpart.py 以 Non-GUI 的模式執行 NX12, 將可直接建立 cube.prt

#
import math
import NXOpen
import NXOpen.Annotations
import NXOpen.Features
import NXOpen.GeometricUtilities
import NXOpen.Preferences
import NXOpen.UF

def main() : 
    
    theUI = NXOpen.UI.GetUI()
    theMsgBox = theUI.NXMessageBox
    theMsgBox.Show("簡要說明", NXOpen.NXMessageBox.DialogType.Information,"以下流程將建立一個簡單的長方體")
    
    theSession  = NXOpen.Session.GetSession()#try to open new part file to edit (different than assemblyFile)
    NXFile = 'C:/python_journal/newPart.prt'
    #use class method to open new session/workPart
    basepart1, partLoadStatus1 = theSession.Parts.OpenBaseDisplay(NXFile)
    partLoadStatus1.Dispose()
    workPart    = theSession.Parts.Work
    displayPart = theSession.Parts.Display

    # 以下利用 ListingWindow 列出相關資訊, 可用於程式除錯
    theLw = theSession.ListingWindow
    # 開啟 console 將資料印出
    theLw.Open()
    theLw.WriteLine("theSession 變數目前為: "+str(theSession))
    
    # 若直接在 NX12 中執行
    #workPart = theSession.Parts.Work
    # ----------------------------------------------
    #   Menu: Insert-&gt;Sketch...
    # ----------------------------------------------
    markId1 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Start")
    
    sketchInPlaceBuilder1 = workPart.Sketches.CreateSketchInPlaceBuilder2(NXOpen.Sketch.Null)
    
    origin1 = NXOpen.Point3d(0.0, 0.0, 0.0)
    normal1 = NXOpen.Vector3d(0.0, 0.0, 1.0)
    plane1 = workPart.Planes.CreatePlane(origin1, normal1, NXOpen.SmartObject.UpdateOption.WithinModeling)
    
    sketchInPlaceBuilder1.PlaneReference = plane1
    
    unit1 = workPart.UnitCollection.FindObject("MilliMeter")
    
    sketchAlongPathBuilder1 = workPart.Sketches.CreateSketchAlongPathBuilder(NXOpen.Sketch.Null)

    datumAxis1 = workPart.Datums.FindObject("DATUM_CSYS(0) X axis")
    direction1 = workPart.Directions.CreateDirection(datumAxis1, NXOpen.Sense.Forward, NXOpen.SmartObject.UpdateOption.WithinModeling)
    
    datumPlane1 = workPart.Datums.FindObject("DATUM_CSYS(0) XY plane")
    datumCsys1 = workPart.Features.FindObject("DATUM_CSYS(0)")
    point1 = datumCsys1.FindObject("POINT 1")
    xform1 = workPart.Xforms.CreateXformByPlaneXDirPoint(datumPlane1, direction1, point1, NXOpen.SmartObject.UpdateOption.WithinModeling, 0.625, False, False)
    
    cartesianCoordinateSystem1 = workPart.CoordinateSystems.CreateCoordinateSystem(xform1, NXOpen.SmartObject.UpdateOption.WithinModeling)
    
    sketchInPlaceBuilder1.Csystem = cartesianCoordinateSystem1

    origin3 = NXOpen.Point3d(0.0, 0.0, 0.0)
    normal3 = NXOpen.Vector3d(0.0, 0.0, 1.0)
    plane3 = workPart.Planes.CreatePlane(origin3, normal3, NXOpen.SmartObject.UpdateOption.WithinModeling)
    
    plane3.SetMethod(NXOpen.PlaneTypes.MethodType.Coincident)
    
    geom2 = [NXOpen.NXObject.Null] * 1 
    geom2[0] = datumPlane1
    plane3.SetGeometry(geom2)
    
    plane3.SetAlternate(NXOpen.PlaneTypes.AlternateType.One)
    
    plane3.Evaluate()

    # ----------------------------------------------
    #   Menu: Insert-&gt;Sketch Curve-&gt;Rectangle...
    # ----------------------------------------------

    markId3 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Create Sketch")

    nXObject1 = sketchInPlaceBuilder1.Commit()
    
    sketch1 = nXObject1
    feature1 = sketch1.Feature
    
    sketch1.Activate(NXOpen.Sketch.ViewReorient.TrueValue)
    
    theSession.DeleteUndoMark(markId3, None)
    
    theSession.SetUndoMarkName(markId1, "Create Sketch")
    
    sketchInPlaceBuilder1.Destroy()
    
    sketchAlongPathBuilder1.Destroy()
        
    plane3.DestroyPlane()
    
    markId5 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Profile short list")
    
    markId6 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Create Rectangle")
    
    theSession.SetUndoMarkVisibility(markId6, "Create Rectangle", NXOpen.Session.MarkVisibility.Visible)
    
    # ----------------------------------------------
    # Creating rectangle using By 2 Points method 
    # ----------------------------------------------
    startPoint1 = NXOpen.Point3d(-52.0, 42.0, 0.0)
    endPoint1 = NXOpen.Point3d(44.0, 42.0, 0.0)
    line1 = workPart.Curves.CreateLine(startPoint1, endPoint1)
    
    startPoint2 = NXOpen.Point3d(44.0, 42.0, 0.0)
    endPoint2 = NXOpen.Point3d(44.0, -42.0, 0.0)
    line2 = workPart.Curves.CreateLine(startPoint2, endPoint2)
    
    startPoint3 = NXOpen.Point3d(44.0, -42.0, 0.0)
    endPoint3 = NXOpen.Point3d(-52.0, -42.0, 0.0)
    line3 = workPart.Curves.CreateLine(startPoint3, endPoint3)
    
    startPoint4 = NXOpen.Point3d(-52.0, -42.0, 0.0)
    endPoint4 = NXOpen.Point3d(-52.0, 42.0, 0.0)
    line4 = workPart.Curves.CreateLine(startPoint4, endPoint4)
    
    theSession.ActiveSketch.AddGeometry(line1, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
    
    theSession.ActiveSketch.AddGeometry(line2, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
    
    theSession.ActiveSketch.AddGeometry(line3, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
    
    theSession.ActiveSketch.AddGeometry(line4, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)

    theSession.ActiveSketch.Update()
    
    theSession.Preferences.Sketch.AutoDimensionsToArcCenter = True
    
    geoms1 = [NXOpen.SmartObject.Null] * 4 
    geoms1[0] = line1
    geoms1[1] = line2
    geoms1[2] = line3
    geoms1[3] = line4
    theSession.ActiveSketch.UpdateConstraintDisplay(geoms1)
    # ----------------------------------------------
    #   Menu: File-&gt;Finish Sketch
    # ----------------------------------------------
    sketch2 = theSession.ActiveSketch
    # ----------------------------------------------
    #   Menu: Insert-&gt;Design Feature-&gt;Extrude...
    # ----------------------------------------------
    markId8 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Start")
    
    extrudeBuilder1 = workPart.Features.CreateExtrudeBuilder(NXOpen.Features.Feature.Null)
    
    section1 = workPart.Sections.CreateSection(0.0094999999999999998, 0.01, 0.5)
    
    extrudeBuilder1.Section = section1
    
    extrudeBuilder1.AllowSelfIntersectingSection(True)
    
    unit2 = extrudeBuilder1.Draft.FrontDraftAngle.Units
  
    features1 = [NXOpen.Features.Feature.Null] * 1 
    sketchFeature1 = feature1
    features1[0] = sketchFeature1
    curveFeatureRule1 = workPart.ScRuleFactory.CreateRuleCurveFeature(features1)
    
    section1.AllowSelfIntersection(True)
    
    rules1 = [None] * 1 
    rules1[0] = curveFeatureRule1
    helpPoint1 = NXOpen.Point3d(-52.0, 18.603986789941445, 3.5527136788005009e-15)
    section1.AddToSection(rules1, line4, NXOpen.NXObject.Null, NXOpen.NXObject.Null, helpPoint1, NXOpen.Section.Mode.Create, False)

    direction2 = workPart.Directions.CreateDirection(sketch2, NXOpen.Sense.Forward, NXOpen.SmartObject.UpdateOption.WithinModeling)
    
    extrudeBuilder1.Direction = direction2
    
    extrudeBuilder1.Limits.EndExtend.Value.RightHandSide = "50"

    extrudeBuilder1.ParentFeatureInternal = False
    
    feature2 = extrudeBuilder1.CommitFeature()
    # 將 basepart1 存檔
    newNXFile = 'C:/python_journal/cube.prt'
    basepart1.SaveAs(newNXFile)

    # ----------------------------------------------
    #   Menu: Tools-&gt;Journal-&gt;Stop Recording
    # ----------------------------------------------
    
if __name__ == '__main__':
    main()
</pre>
<p>假如希望利用 <a href="https://mde.tw/cp2019">https://mde.tw/cp2019</a> 中的 Dart 網際或 Flutter 手機程式與伺服器中的 NXOpen Python API 程式互動, 可以利用 Flask 網際程式結合下列 Python API 程式碼, 透過手機介面輸入零組件設計參數, 所完成的零組件則以 STL 或 WRL 格式輸出, 進一步轉入 Webots 執行動態模擬.</p>
<p><a href="http://cd03.kmol.info/NXOpen.UI.html#NXOpen.UI">NXOpen.UI</a></p>
<p><a href="http://cd03.kmol.info/NXOpen.NXMessageBox.html?highlight=messagebox#NXOpen.NXMessageBox">NXMessageBox</a></p>
<p><a href="http://cd03.kmol.info/NXOpen.Session.html?highlight=session#NXOpen.Session">NXOpen.Session</a></p>
<p><a href="http://cd03.kmol.info/NXOpen.Point3d.html?highlight=point3d#NXOpen.Point3d">NXOpen.Point3d</a></p>
<p><a href="http://cd03.kmol.info/NXOpen.Features.FeatureCollection.html?highlight=createextrudebuilder#nxopen-features-featurecollection-createextrudebuilder">CreateExtrudeBuilder</a></p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false"># NX 12.0.2.9
# 提供空檔案 newPart.prt
# 利用 run_journal journal_newpart.py 以 Non-GUI 的模式執行 NX12, 將可直接建立 cube.prt
 
#
import math
import NXOpen
import NXOpen.Annotations
import NXOpen.Features
import NXOpen.GeometricUtilities
import NXOpen.Preferences
import NXOpen.UF
 
def main() : 
     
    theUI = NXOpen.UI.GetUI()
    theMsgBox = theUI.NXMessageBox
    theMsgBox.Show("簡要說明", NXOpen.NXMessageBox.DialogType.Information,"以下流程將建立一個簡單的長方體")
     
    theSession  = NXOpen.Session.GetSession()#try to open new part file to edit (different than assemblyFile)
    NXFile = 'y:/newPart.prt'
    #use class method to open new session/workPart
    basepart1, partLoadStatus1 = theSession.Parts.OpenBaseDisplay(NXFile)
    partLoadStatus1.Dispose()
    workPart    = theSession.Parts.Work
    displayPart = theSession.Parts.Display
 
    # 以下利用 ListingWindow 列出相關資訊, 可用於程式除錯
    theLw = theSession.ListingWindow
    # 開啟 console 將資料印出
    theLw.Open()
    theLw.WriteLine("theSession 變數目前為: "+str(theSession))
     
    # 若直接在 NX12 中執行
    #workPart = theSession.Parts.Work
    # ----------------------------------------------
    #   Menu: Insert-&gt;Sketch...
    # ----------------------------------------------
    markId1 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Start")
     
    sketchInPlaceBuilder1 = workPart.Sketches.CreateSketchInPlaceBuilder2(NXOpen.Sketch.Null)
     
    origin1 = NXOpen.Point3d(0.0, 0.0, 0.0)
    normal1 = NXOpen.Vector3d(0.0, 0.0, 1.0)
    plane1 = workPart.Planes.CreatePlane(origin1, normal1, NXOpen.SmartObject.UpdateOption.WithinModeling)
     
    sketchInPlaceBuilder1.PlaneReference = plane1
     
    unit1 = workPart.UnitCollection.FindObject("MilliMeter")
     
    sketchAlongPathBuilder1 = workPart.Sketches.CreateSketchAlongPathBuilder(NXOpen.Sketch.Null)
 
    datumAxis1 = workPart.Datums.FindObject("DATUM_CSYS(0) X axis")
    direction1 = workPart.Directions.CreateDirection(datumAxis1, NXOpen.Sense.Forward, NXOpen.SmartObject.UpdateOption.WithinModeling)
     
    datumPlane1 = workPart.Datums.FindObject("DATUM_CSYS(0) XY plane")
    datumCsys1 = workPart.Features.FindObject("DATUM_CSYS(0)")
    point1 = datumCsys1.FindObject("POINT 1")
    xform1 = workPart.Xforms.CreateXformByPlaneXDirPoint(datumPlane1, direction1, point1, NXOpen.SmartObject.UpdateOption.WithinModeling, 0.625, False, False)
     
    cartesianCoordinateSystem1 = workPart.CoordinateSystems.CreateCoordinateSystem(xform1, NXOpen.SmartObject.UpdateOption.WithinModeling)
     
    sketchInPlaceBuilder1.Csystem = cartesianCoordinateSystem1
 
    origin3 = NXOpen.Point3d(0.0, 0.0, 0.0)
    normal3 = NXOpen.Vector3d(0.0, 0.0, 1.0)
    plane3 = workPart.Planes.CreatePlane(origin3, normal3, NXOpen.SmartObject.UpdateOption.WithinModeling)
     
    plane3.SetMethod(NXOpen.PlaneTypes.MethodType.Coincident)
     
    geom2 = [NXOpen.NXObject.Null] * 1
    geom2[0] = datumPlane1
    plane3.SetGeometry(geom2)
     
    plane3.SetAlternate(NXOpen.PlaneTypes.AlternateType.One)
     
    plane3.Evaluate()
 
    # ----------------------------------------------
    #   Menu: Insert-&gt;Sketch Curve-&gt;Rectangle...
    # ----------------------------------------------
 
    markId3 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Create Sketch")
 
    nXObject1 = sketchInPlaceBuilder1.Commit()
     
    sketch1 = nXObject1
    feature1 = sketch1.Feature
     
    sketch1.Activate(NXOpen.Sketch.ViewReorient.TrueValue)
     
    theSession.DeleteUndoMark(markId3, None)
     
    theSession.SetUndoMarkName(markId1, "Create Sketch")
     
    sketchInPlaceBuilder1.Destroy()
     
    sketchAlongPathBuilder1.Destroy()
         
    plane3.DestroyPlane()
     
    markId5 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Profile short list")
     
    markId6 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Create Rectangle")
     
    theSession.SetUndoMarkVisibility(markId6, "Create Rectangle", NXOpen.Session.MarkVisibility.Visible)
     
    # ----------------------------------------------
    # Creating rectangle using By 2 Points method 
    # ----------------------------------------------
    startPoint1 = NXOpen.Point3d(-52.0, 42.0, 0.0)
    endPoint1 = NXOpen.Point3d(44.0, 42.0, 0.0)
    line1 = workPart.Curves.CreateLine(startPoint1, endPoint1)
     
    startPoint2 = NXOpen.Point3d(44.0, 42.0, 0.0)
    endPoint2 = NXOpen.Point3d(44.0, -42.0, 0.0)
    line2 = workPart.Curves.CreateLine(startPoint2, endPoint2)
     
    startPoint3 = NXOpen.Point3d(44.0, -42.0, 0.0)
    endPoint3 = NXOpen.Point3d(-52.0, -42.0, 0.0)
    line3 = workPart.Curves.CreateLine(startPoint3, endPoint3)
     
    startPoint4 = NXOpen.Point3d(-52.0, -42.0, 0.0)
    endPoint4 = NXOpen.Point3d(-52.0, 42.0, 0.0)
    line4 = workPart.Curves.CreateLine(startPoint4, endPoint4)
     
    theSession.ActiveSketch.AddGeometry(line1, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
     
    theSession.ActiveSketch.AddGeometry(line2, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
     
    theSession.ActiveSketch.AddGeometry(line3, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
     
    theSession.ActiveSketch.AddGeometry(line4, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
 
    theSession.ActiveSketch.Update()
     
    theSession.Preferences.Sketch.AutoDimensionsToArcCenter = True
     
    geoms1 = [NXOpen.SmartObject.Null] * 4
    geoms1[0] = line1
    geoms1[1] = line2
    geoms1[2] = line3
    geoms1[3] = line4
    theSession.ActiveSketch.UpdateConstraintDisplay(geoms1)
    # ----------------------------------------------
    #   Menu: File-&gt;Finish Sketch
    # ----------------------------------------------
    sketch2 = theSession.ActiveSketch
    # ----------------------------------------------
    #   Menu: Insert-&gt;Design Feature-&gt;Extrude...
    # ----------------------------------------------
    markId8 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Start")
     
    extrudeBuilder1 = workPart.Features.CreateExtrudeBuilder(NXOpen.Features.Feature.Null)
     
    section1 = workPart.Sections.CreateSection(0.0094999999999999998, 0.01, 0.5)
     
    extrudeBuilder1.Section = section1
     
    extrudeBuilder1.AllowSelfIntersectingSection(True)
     
    unit2 = extrudeBuilder1.Draft.FrontDraftAngle.Units
   
    features1 = [NXOpen.Features.Feature.Null] * 1
    sketchFeature1 = feature1
    features1[0] = sketchFeature1
    curveFeatureRule1 = workPart.ScRuleFactory.CreateRuleCurveFeature(features1)
     
    section1.AllowSelfIntersection(True)
     
    rules1 = [None] * 1
    rules1[0] = curveFeatureRule1
    helpPoint1 = NXOpen.Point3d(-52.0, 18.603986789941445, 3.5527136788005009e-15)
    section1.AddToSection(rules1, line4, NXOpen.NXObject.Null, NXOpen.NXObject.Null, helpPoint1, NXOpen.Section.Mode.Create, False)
 
    direction2 = workPart.Directions.CreateDirection(sketch2, NXOpen.Sense.Forward, NXOpen.SmartObject.UpdateOption.WithinModeling)
     
    extrudeBuilder1.Direction = direction2
     
    extrudeBuilder1.Limits.EndExtend.Value.RightHandSide = "50"
 
    extrudeBuilder1.ParentFeatureInternal = False
     
    feature2 = extrudeBuilder1.CommitFeature()
    # 將 basepart1 存檔
    #newNXFile = 'y:/cube.prt'
    #basepart1.SaveAs(newNXFile)
    # 將零件檔案存為 wrl 格式
    theUFSession = NXOpen.UF.UFSession.GetUFSession()
    UF_STD_OUTPUT_VRML_2 = 8
    theUFSession.Std.CreateVrmlFile("y:/cube.wrl", 1.0, UF_STD_OUTPUT_VRML_2)
    print("已經將零件轉為 wrl 檔案")
    # ----------------------------------------------
    #   Menu: Tools-&gt;Journal-&gt;Stop Recording
    # ----------------------------------------------
     
if __name__ == '__main__':
    main()</pre>
<h4>參考資料</h4>
<p>NXOpen VB 轉為 Python:</p>
<p style="padding-left: 30px;"><a href="https://community.sw.siemens.com/s/question/0D54O000061xRnYSAU/convert-vb-to-python">https://community.sw.siemens.com/s/question/0D54O000061xRnYSAU/convert-vb-to-python</a></p><br />NX << <a href='NX.html'>Previous</a> <a href='TeX.html'>Next</a> >> TeX</div>
        
    <!-- footer -->
      <div class="container">
        <div class="row pt-3 mx-auto">
            <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
      </div>
    <!-- for footer -->
    
        </div> <!-- for site wrap -->
            <!-- <script src="../cmsimde/static/chimper/js/jquery-3.3.1.min.js"></script> -->
            <script src="../cmsimde/static/chimper/js/jquery-migrate-3.0.1.min.js"></script>
            <script src="../cmsimde/static/chimper/js/jquery-ui.js"></script>
            <script src="../cmsimde/static/chimper/js/popper.min.js"></script>
            <script src="../cmsimde/static/chimper/js/bootstrap.min.js"></script>
            <script src="../cmsimde/static/chimper/js/owl.carousel.min.js"></script>
            <script src="../cmsimde/static/chimper/js/jquery.stellar.min.js"></script>
            <script src="../cmsimde/static/chimper/js/jquery.countdown.min.js"></script>
            <script src="../cmsimde/static/chimper/js/jquery.magnific-popup.min.js"></script>
            <script src="../cmsimde/static/chimper/js/bootstrap-datepicker.min.js"></script>
            <script src="../cmsimde/static/chimper/js/aos.js"></script>
            <!--
            <script src="../cmsimde/static/chimper/js/typed.js"></script>
                    <script>
                    var typed = new Typed('.typed-words', {
                    strings: ["Web Apps"," WordPress"," Mobile Apps"],
                    typeSpeed: 80,
                    backSpeed: 80,
                    backDelay: 4000,
                    startDelay: 1000,
                    loop: true,
                    showCursor: true
                    });
                    </script>
            -->
            <script src="../cmsimde/static/chimper/js/main.js"></script>
        </body></html>
        